### ISSUE TITLE
Error with metadata.common.movieposterdb.com dependence while installing

### ISSUE THREAD

**Issue by quijot** [MaDDoGo/metadata.filmaffinity.com#68]
Having problem with metadata.common.movieposterdb.com dependence while installing. I think that dependence does not exist anymore.
Error says: "Dependence metadata.common.movieposterdb.com could not be satisfied."
![2017-07-27--1501199774_1366x768_scrot](https://user-images.githubusercontent.com/1616997/28696832-7fb4a07a-730e-11e7-9421-fbcb60fbfdc5.png)

**Comment by pancheto** [comment]
the problem may have appeared due to the recent removal from the official Kodi repository of the dependencies needed to obtain posters from movieposterdb (plugin named metadata.common.movieposterdb.com). I've removed all movieposterdb references from the scraper, so this option will no longer exist, but the scraper is perfectly installable and functional now.

**Comment by quijot** [comment]
Great! I suspected it would be like this. Thanks!
